from __future__ import annotations

from html import escape
from urllib.parse import urlencode

from .assessment import FLAG_QUESTIONS, SCORE_QUESTIONS
from .contracts import AssessmentResult, BooleanDecision, Score


SCORE_LABELS = {
    "security_risk": "Security",
    "performance_risk": "Performance",
    "change_impact": "Change impact",
    "maintainability_risk": "Maintainability",
    "overall_risk": "Overall risk",
}

FLAG_LABELS = {
    "authentication_or_authorization": "Auth / access",
    "sensitive_data": "Sensitive data",
    "public_contract": "Public contract",
    "dependency_or_supply_chain": "Supply chain",
    "concurrency_or_resource_use": "Concurrency / resources",
    "deployment_or_migration": "Deployment / migration",
}

CLASSIFICATION_COLORS = {
    "trivial": "brightgreen",
    "routine": "green",
    "significant": "yellow",
    "high_risk": "orange",
    "critical": "red",
}


def render_github_comment(result: AssessmentResult) -> str:
    """Render a compact GitHub-flavored Markdown risk summary."""
    classification = result.classification.value
    lines = [
        "## S1 risk assessment",
        "",
        _badge(
            "Classification",
            classification.replace("_", " "),
            CLASSIFICATION_COLORS.get(classification, "lightgrey"),
            (
                f"Classification: {classification.replace('_', ' ')}. "
                f"Confidence: {_percent(result.classification.confidence)}."
            ),
        )
        + " "
        + _boolean_badge(
            "Deeper review",
            result.deeper_review,
            true_message="required",
            false_message="not required",
            true_color="orange",
            description="Whether deeper human review or additional validation is warranted.",
        ),
        "",
        "**Risk factors**",
        "",
        " ".join(
            _score_badge(name, score) for name, score in result.scores.items()
        )
        or "_No risk scores returned._",
        "",
        "**Flags**",
        "",
        " ".join(
            _flag_badge(name, decision)
            for name, decision in result.risk_flags.items()
        )
        or _badge("Risk flags", "none", "brightgreen", "No risk flags were returned."),
        "",
        _footer(result),
    ]
    return "\n".join(lines)


def _score_badge(name: str, score: Score) -> str:
    label = SCORE_LABELS.get(name, _humanize(name))
    value = f"{score.value:g}/5"
    description = SCORE_QUESTIONS.get(name, f"Risk dimension: {_humanize(name)}.")
    title = (
        f"{description} Score: {score.value:g} out of 5. "
        f"Confidence: {_percent(score.confidence)}."
    )
    return _badge(label, value, _score_color(score.value), title)


def _flag_badge(name: str, decision: BooleanDecision) -> str:
    label = FLAG_LABELS.get(name, _humanize(name))
    description = FLAG_QUESTIONS.get(name, f"Risk flag: {_humanize(name)}.")
    return _boolean_badge(
        label,
        decision,
        true_message="flagged",
        false_message="clear",
        true_color="red",
        description=description,
    )


def _boolean_badge(
    label: str,
    decision: BooleanDecision,
    *,
    true_message: str,
    false_message: str,
    true_color: str,
    description: str,
) -> str:
    message = true_message if decision.value else false_message
    color = true_color if decision.value else "brightgreen"
    title = (
        f"{description} Decision: {message}. "
        f"Probability: {_percent(decision.probability)}."
    )
    return _badge(label, message, color, title)


def _badge(label: str, message: str, color: str, title: str) -> str:
    url = "https://img.shields.io/static/v1?" + urlencode(
        {"label": label, "message": message, "color": color}
    )
    alt = _markdown_text(f"{label}: {message}")
    tooltip = _markdown_title(title)
    return f'![{alt}]({url} "{tooltip}")'


def _score_color(value: float) -> str:
    if value <= 1:
        return "brightgreen"
    if value <= 2:
        return "green"
    if value <= 3:
        return "yellow"
    if value <= 4:
        return "orange"
    return "red"


def _footer(result: AssessmentResult) -> str:
    source = f"{escape(result.provider)} / {escape(result.model)}"
    if result.execution is None:
        return f"<sub>Generated by S1 · {source}</sub>"
    chunks = result.execution.chunks_assessed
    chunk_text = f"{chunks} diff chunk{'s' if chunks != 1 else ''}"
    return f"<sub>Generated by S1 · {source} · {chunk_text}</sub>"


def _percent(value: float) -> str:
    return f"{value:.0%}"


def _humanize(value: str) -> str:
    return value.replace("_", " ").capitalize()


def _markdown_text(value: str) -> str:
    return value.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]")


def _markdown_title(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
